const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_ERROR = 'SIGNUP_ERROR';
const AUTH_USER = 'AUTH_USER';
const UNAUTH_USER = 'UNAUTH_USER';
const SIGNIN_ERROR = 'SIGNIN_ERROR';
const INCREASE_PORTFOLIO_COUNTER = 'INCREASE_PORTFOLIO_COUNTER';
const DECREASE_PORTFOLIO_COUNTER = 'DECREASE_PORTFOLIO_COUNTER';

module.exports = {
  SIGNUP_SUCCESS,
  SIGNUP_ERROR,
  AUTH_USER,
  UNAUTH_USER,
  SIGNIN_ERROR,
  INCREASE_PORTFOLIO_COUNTER,
  DECREASE_PORTFOLIO_COUNTER
}