const AUTH_USER = 'AUTH_USER';
const SIGNIN_ERROR = 'SIGNIN_ERROR';
const INCREASE_USER_COUNTER = 'INCREASE_USER_COUNTER';
const DECREASE_USER_COUNTER = 'DECREASE_USER_COUNTER';
const INCREASE_PORTFOLIO_COUNTER = 'INCREASE_PORTFOLIO_COUNTER';
const DECREASE_PORTFOLIO_COUNTER = 'DECREASE_PORTFOLIO_COUNTER';

module.exports = {
  AUTH_USER,
  SIGNIN_ERROR,
  INCREASE_USER_COUNTER,
  DECREASE_USER_COUNTER,
  INCREASE_PORTFOLIO_COUNTER,
  DECREASE_PORTFOLIO_COUNTER
}