const INCREASE_USER_COUNTER = 'INCREASE_USER_COUNTER';
const DECREASE_USER_COUNTER = 'DECREASE_USER_COUNTER';
const INCREASE_PORTFOLIO_COUNTER = 'INCREASE_PORTFOLIO_COUNTER';
const DECREASE_PORTFOLIO_COUNTER = 'DECREASE_PORTFOLIO_COUNTER';

module.exports = {
  INCREASE_USER_COUNTER,
  DECREASE_USER_COUNTER,
  INCREASE_PORTFOLIO_COUNTER,
  DECREASE_PORTFOLIO_COUNTER
}